-- Penal code - the charge catalogue the MDT sentences against.
--
-- This is a STATIC config, not a database table. An officer picking charges on a report resolves
-- them from here, and the report then stores its own copy of every line it used (code, label,
-- class, months, fine). That denormalised copy is what makes editing this file safe: retune a
-- charge and every report already filed keeps the numbers it was filed under, so a sentence is
-- never quietly rewritten under a case that has already been decided.
--
--   code         the reference an officer types and a warrant cites; must be unique
--   label        what the charge is called
--   class        'felony' | 'misdemeanor' | 'infraction' - drives the counters and the colour
--   months       custodial term this charge contributes, per count
--   fine         monetary penalty this charge contributes, per count
--   description  one line explaining what the charge covers, shown in the penal code browser
--
-- Order does not matter: the terminal groups by class and sorts by code.
--
-- This file is the catalogue every server STARTS from. Anyone holding offences.manage
-- (configs/mdt.lua) can retune a charge, add one or hide one from the terminal itself, and
-- those changes are stored in phone_mdt_penal_overrides and laid over this file. Resetting a
-- charge in the terminal drops it back to the figures below, so editing this file still works.

return {
    -- Felonies
    { code = 'PC 103',  label = 'Aggravated Assault',                               class = 'felony',      months = 24,  fine = 1500,  description = 'Recklessly causing serious bodily injury in the course of a confrontation.' },
    { code = 'PC 104',  label = 'Assault With a Deadly Weapon',                     class = 'felony',      months = 32,  fine = 4000,  description = 'Causing or attempting to cause injury while using or displaying a weapon.' },
    { code = 'PC 105',  label = 'Assault on a Peace Officer',                       class = 'felony',      months = 40,  fine = 5000,  description = 'Assaulting a law enforcement officer who is on duty.' },
    { code = 'PC 106',  label = 'Assault on a Medical Responder',                   class = 'felony',      months = 36,  fine = 4500,  description = 'Assaulting a paramedic or fire responder who is on duty.' },
    { code = 'PC 109',  label = 'Torture',                                          class = 'felony',      months = 45,  fine = 6000,  description = 'Inflicting prolonged physical or mental suffering on a restrained person.' },
    { code = 'PC 110',  label = 'Involuntary Manslaughter',                         class = 'felony',      months = 60,  fine = 8000,  description = 'Causing the death of another person through recklessness rather than intent.' },
    { code = 'PC 111',  label = 'Vehicular Manslaughter',                           class = 'felony',      months = 70,  fine = 8000,  description = 'Causing the death of another person while operating a vehicle recklessly.' },
    { code = 'PC 112',  label = 'Attempted Murder',                                 class = 'felony',      months = 55,  fine = 9000,  description = 'Attacking another person with a clear intent to kill them.' },
    { code = 'PC 113',  label = 'Second Degree Murder',                             class = 'felony',      months = 95,  fine = 15000, description = 'An intentional killing carried out without planning.' },
    { code = 'PC 114',  label = 'First Degree Murder',                              class = 'felony',      months = 110, fine = 18000, description = 'A killing that is willful, deliberate and planned in advance.' },
    { code = 'PC 115',  label = 'Murder of a Peace Officer',                        class = 'felony',      months = 130, fine = 25000, description = 'Killing a law enforcement officer who is on duty.' },
    { code = 'PC 116',  label = 'Attempted Murder of a Peace Officer',              class = 'felony',      months = 70,  fine = 12000, description = 'Attacking an on-duty officer with a clear intent to kill them.' },
    { code = 'PC 117',  label = 'Accessory to Murder',                              class = 'felony',      months = 55,  fine = 8000,  description = 'Assisting, sheltering or acting alongside the person who carried out a killing.' },
    { code = 'PC 119',  label = 'Kidnapping',                                       class = 'felony',      months = 20,  fine = 1500,  description = 'Taking a person and moving them against their will.' },
    { code = 'PC 120',  label = 'Attempted Kidnapping',                             class = 'felony',      months = 12,  fine = 900,   description = 'Trying and failing to take a person against their will.' },
    { code = 'PC 121',  label = 'Accessory to Kidnapping',                          class = 'felony',      months = 10,  fine = 800,   description = 'Assisting in the taking of a person against their will.' },
    { code = 'PC 122',  label = 'Hostage Taking',                                   class = 'felony',      months = 26,  fine = 2000,  description = 'Holding a person against their will to force a payment or an outcome.' },
    { code = 'PC 123',  label = 'Gang Related Shooting',                            class = 'felony',      months = 35,  fine = 3000,  description = 'Discharging a firearm in the course of organised criminal activity.' },
    { code = 'PC 124',  label = 'Stalking',                                         class = 'felony',      months = 30,  fine = 1800,  description = 'Repeatedly following or monitoring a person without their consent.' },
    { code = 'PC 126',  label = 'Desecration of Human Remains',                     class = 'felony',      months = 22,  fine = 2000,  description = 'Disturbing, moving or damaging the remains of a deceased person.' },
    { code = 'PC 127',  label = 'Cannibalism',                                      class = 'felony',      months = 100, fine = 20000, description = 'Consuming the flesh of another person.' },
    { code = 'PC 203',  label = 'Grand Larceny',                                    class = 'felony',      months = 40,  fine = 6000,  description = 'Taking property of very high value.' },
    { code = 'PC 204',  label = 'Vehicle Theft',                                    class = 'felony',      months = 15,  fine = 1200,  description = 'Taking a vehicle belonging to another person without their permission.' },
    { code = 'PC 205',  label = 'Armed Vehicle Theft',                              class = 'felony',      months = 32,  fine = 3500,  description = 'Taking a vehicle without permission while carrying a weapon.' },
    { code = 'PC 206',  label = 'Carjacking',                                       class = 'felony',      months = 30,  fine = 2500,  description = 'Forcing an occupant out of their vehicle in order to take it.' },
    { code = 'PC 207',  label = 'Theft of an Aircraft',                             class = 'felony',      months = 24,  fine = 2000,  description = 'Taking an aircraft without the owner permission.' },
    { code = 'PC 208',  label = 'Theft of a Vessel',                                class = 'felony',      months = 20,  fine = 1500,  description = 'Taking a boat or watercraft without the owner permission.' },
    { code = 'PC 210',  label = 'Robbery',                                          class = 'felony',      months = 25,  fine = 2000,  description = 'Taking property from a person or place by force or the threat of force.' },
    { code = 'PC 211',  label = 'Armed Robbery',                                    class = 'felony',      months = 32,  fine = 3500,  description = 'Taking property by force while carrying or displaying a weapon.' },
    { code = 'PC 212',  label = 'Attempted Robbery',                                class = 'felony',      months = 18,  fine = 1200,  description = 'Trying and failing to take property by force.' },
    { code = 'PC 213',  label = 'Accessory to Robbery',                             class = 'felony',      months = 14,  fine = 1200,  description = 'Assisting in a robbery without carrying it out.' },
    { code = 'PC 216',  label = 'Possession of Government Property',                class = 'felony',      months = 18,  fine = 1500,  description = 'Holding equipment issued only to government employees.' },
    { code = 'PC 218',  label = 'Sale of Stolen Property',                          class = 'felony',      months = 18,  fine = 1500,  description = 'Selling or trading property known to be stolen.' },
    { code = 'PC 220',  label = 'Looting',                                          class = 'felony',      months = 20,  fine = 1800,  description = 'Taking property from the scene of an emergency, disaster or public disorder.' },
    { code = 'PC 303',  label = 'Identity Theft',                                   class = 'felony',      months = 20,  fine = 2000,  description = 'Using the identity of another person without their consent.' },
    { code = 'PC 307',  label = 'Impersonating a Peace Officer',                    class = 'felony',      months = 26,  fine = 3000,  description = 'Falsely presenting yourself as a law enforcement officer.' },
    { code = 'PC 308',  label = 'Impersonating a Medical Professional',             class = 'felony',      months = 24,  fine = 2500,  description = 'Falsely presenting yourself as a doctor or paramedic.' },
    { code = 'PC 309',  label = 'Impersonating a Judge',                            class = 'felony',      months = 32,  fine = 4000,  description = 'Falsely presenting yourself as a member of the judiciary.' },
    { code = 'PC 310',  label = 'Extortion',                                        class = 'felony',      months = 22,  fine = 1500,  description = 'Demanding money or property under threat of harm or exposure.' },
    { code = 'PC 311',  label = 'Money Laundering',                                 class = 'felony',      months = 40,  fine = 8000,  description = 'Passing criminal proceeds through legitimate accounts to disguise their origin.' },
    { code = 'PC 312',  label = 'Embezzlement',                                     class = 'felony',      months = 45,  fine = 10000, description = 'Diverting funds held in trust into personal accounts.' },
    { code = 'PC 313',  label = 'Insurance Fraud',                                  class = 'felony',      months = 20,  fine = 2500,  description = 'Making a knowingly false claim against an insurer.' },
    { code = 'PC 314',  label = 'Tax Evasion',                                      class = 'felony',      months = 24,  fine = 5000,  description = 'Deliberately concealing income or assets from the city.' },
    { code = 'PC 315',  label = 'Counterfeiting',                                   class = 'felony',      months = 35,  fine = 6000,  description = 'Producing imitation currency or official documents.' },
    { code = 'PC 405',  label = 'Arson',                                            class = 'felony',      months = 20,  fine = 2500,  description = 'Deliberately setting fire to property.' },
    { code = 'PC 406',  label = 'Aggravated Arson',                                 class = 'felony',      months = 45,  fine = 8000,  description = 'Setting fire to a property while people are inside it.' },
    { code = 'PC 408',  label = 'Felony Trespassing',                               class = 'felony',      months = 15,  fine = 1500,  description = 'Repeatedly entering property after being formally excluded from it.' },
    { code = 'PC 410',  label = 'Tampering With Utilities',                         class = 'felony',      months = 18,  fine = 2000,  description = 'Interfering with power, water or communications infrastructure.' },
    { code = 'PC 504',  label = 'Felony Obstruction of Justice',                    class = 'felony',      months = 16,  fine = 1200,  description = 'Hindering a lawful investigation by force or by threat.' },
    { code = 'PC 505',  label = 'Evidence Tampering',                               class = 'felony',      months = 20,  fine = 1500,  description = 'Destroying, hiding or altering evidence in an investigation.' },
    { code = 'PC 506',  label = 'Witness Tampering',                                class = 'felony',      months = 26,  fine = 3000,  description = 'Coaching, bribing or intimidating a witness.' },
    { code = 'PC 509',  label = 'Perjury',                                          class = 'felony',      months = 22,  fine = 2500,  description = 'Making a false statement while under oath.' },
    { code = 'PC 513',  label = 'Violating a Restraining Order',                    class = 'felony',      months = 20,  fine = 2500,  description = 'Approaching a person a court has ordered you to stay away from.' },
    { code = 'PC 514',  label = 'Escape From Custody',                              class = 'felony',      months = 14,  fine = 1000,  description = 'Leaving lawful custody without authorisation.' },
    { code = 'PC 515',  label = 'Escape From a Correctional Facility',              class = 'felony',      months = 32,  fine = 3000,  description = 'Leaving a state or county detention facility without release.' },
    { code = 'PC 516',  label = 'Aiding an Escape',                                 class = 'felony',      months = 28,  fine = 2500,  description = 'Assisting a person to leave lawful custody.' },
    { code = 'PC 517',  label = 'Attempted Jailbreak',                              class = 'felony',      months = 22,  fine = 2000,  description = 'Attempting to remove a person from a detention facility.' },
    { code = 'PC 518',  label = 'Bribery of a Public Official',                     class = 'felony',      months = 24,  fine = 4000,  description = 'Offering money or favours to influence an official act.' },
    { code = 'PC 519',  label = 'Public Corruption',                                class = 'felony',      months = 55,  fine = 12000, description = 'Using a public office for personal gain.' },
    { code = 'PC 525',  label = 'Contraband in a Government Facility',              class = 'felony',      months = 24,  fine = 1500,  description = 'Carrying prohibited items inside a government building.' },
    { code = 'PC 526',  label = 'Unlawful Practice of a Profession',                class = 'felony',      months = 16,  fine = 1500,  description = 'Providing a licensed service without holding the licence.' },
    { code = 'PC 527',  label = 'Vigilantism',                                      class = 'felony',      months = 28,  fine = 1800,  description = 'Enforcing the law without any legal authority to do so.' },
    { code = 'PC 608',  label = 'Inciting a Riot',                                  class = 'felony',      months = 26,  fine = 2500,  description = 'Urging a crowd toward violence or destruction.' },
    { code = 'PC 609',  label = 'Rioting',                                          class = 'felony',      months = 20,  fine = 1800,  description = 'Taking part in a violent public disturbance.' },
    { code = 'PC 703',  label = 'Commercial Cultivation of Marijuana',              class = 'felony',      months = 26,  fine = 2000,  description = 'Growing marijuana plants at a scale intended for supply.' },
    { code = 'PC 704',  label = 'Manufacture of Marijuana Products',                class = 'felony',      months = 18,  fine = 1200,  description = 'Processing marijuana into a saleable product.' },
    { code = 'PC 705',  label = 'Possession of Marijuana for Supply',               class = 'felony',      months = 28,  fine = 3000,  description = 'Holding marijuana in a quantity indicating an intent to supply.' },
    { code = 'PC 707',  label = 'Manufacture of Cocaine',                           class = 'felony',      months = 26,  fine = 1800,  description = 'Processing coca product into a saleable form.' },
    { code = 'PC 708',  label = 'Possession of Cocaine for Supply',                 class = 'felony',      months = 34,  fine = 4500,  description = 'Holding cocaine in a quantity indicating an intent to supply.' },
    { code = 'PC 710',  label = 'Manufacture of Methamphetamine',                   class = 'felony',      months = 28,  fine = 2000,  description = 'Producing methamphetamine from precursor chemicals.' },
    { code = 'PC 711',  label = 'Possession of Methamphetamine for Supply',         class = 'felony',      months = 34,  fine = 4500,  description = 'Holding methamphetamine in a quantity indicating an intent to supply.' },
    { code = 'PC 713',  label = 'Manufacture of Heroin',                            class = 'felony',      months = 30,  fine = 2200,  description = 'Processing opiate product into a saleable form.' },
    { code = 'PC 714',  label = 'Possession of Heroin for Supply',                  class = 'felony',      months = 36,  fine = 5000,  description = 'Holding heroin in a quantity indicating an intent to supply.' },
    { code = 'PC 716',  label = 'Manufacture of Ecstasy',                           class = 'felony',      months = 26,  fine = 1800,  description = 'Producing ecstasy tablets from precursor chemicals.' },
    { code = 'PC 717',  label = 'Possession of Ecstasy for Supply',                 class = 'felony',      months = 34,  fine = 4500,  description = 'Holding ecstasy in a quantity indicating an intent to supply.' },
    { code = 'PC 719',  label = 'Manufacture of Prescription Medication',           class = 'felony',      months = 26,  fine = 1800,  description = 'Producing prescription medication outside a licensed pharmacy.' },
    { code = 'PC 720',  label = 'Possession of Prescription Medication for Supply', class = 'felony',      months = 32,  fine = 4000,  description = 'Holding prescription medication in a quantity indicating an intent to supply.' },
    { code = 'PC 722',  label = 'Possession of Psilocybin for Supply',              class = 'felony',      months = 30,  fine = 3500,  description = 'Holding psilocybin in a quantity indicating an intent to supply.' },
    { code = 'PC 724',  label = 'Drug Trafficking',                                 class = 'felony',      months = 48,  fine = 9000,  description = 'Moving controlled substances in bulk.' },
    { code = 'PC 725',  label = 'Operating a Drug Laboratory',                      class = 'felony',      months = 40,  fine = 7000,  description = 'Running a site set up for the manufacture of controlled substances.' },
    { code = 'PC 726',  label = 'Distribution to a Minor',                          class = 'felony',      months = 45,  fine = 8000,  description = 'Supplying a controlled substance to a person under age.' },
    { code = 'PC 801',  label = 'Possession of a Class A Firearm',                  class = 'felony',      months = 10,  fine = 600,   description = 'Holding a small calibre handgun without a licence.' },
    { code = 'PC 802',  label = 'Possession of a Class B Firearm',                  class = 'felony',      months = 16,  fine = 1200,  description = 'Holding a large calibre handgun without a licence.' },
    { code = 'PC 803',  label = 'Possession of a Class C Firearm',                  class = 'felony',      months = 30,  fine = 4000,  description = 'Holding an automatic or military grade firearm without a licence.' },
    { code = 'PC 804',  label = 'Possession of a Class D Firearm',                  class = 'felony',      months = 24,  fine = 2000,  description = 'Holding a shotgun or rifle without a licence.' },
    { code = 'PC 805',  label = 'Sale of a Class A Firearm',                        class = 'felony',      months = 16,  fine = 1200,  description = 'Selling a small calibre handgun without a dealer licence.' },
    { code = 'PC 806',  label = 'Sale of a Class B Firearm',                        class = 'felony',      months = 22,  fine = 2200,  description = 'Selling a large calibre handgun without a dealer licence.' },
    { code = 'PC 807',  label = 'Sale of a Class C Firearm',                        class = 'felony',      months = 36,  fine = 7000,  description = 'Selling an automatic or military grade firearm without a dealer licence.' },
    { code = 'PC 808',  label = 'Sale of a Class D Firearm',                        class = 'felony',      months = 30,  fine = 3500,  description = 'Selling a shotgun or rifle without a dealer licence.' },
    { code = 'PC 809',  label = 'Weapon Trafficking',                               class = 'felony',      months = 50,  fine = 10000, description = 'Moving firearms in bulk for supply.' },
    { code = 'PC 810',  label = 'Possession of a Defaced Firearm',                  class = 'felony',      months = 20,  fine = 1800,  description = 'Holding a firearm whose serial number has been removed or altered.' },
    { code = 'PC 815',  label = 'Possession of Explosives',                         class = 'felony',      months = 28,  fine = 3000,  description = 'Holding explosive material without a licence.' },
    { code = 'PC 816',  label = 'Criminal Use of Explosives',                       class = 'felony',      months = 35,  fine = 4000,  description = 'Using explosives in the course of committing another offence.' },
    { code = 'PC 817',  label = 'Possession of a Prohibited Weapon',                class = 'felony',      months = 26,  fine = 2500,  description = 'Holding a weapon that may not be owned under any licence.' },
    { code = 'PC 818',  label = 'Insurrection',                                     class = 'felony',      months = 120, fine = 25000, description = 'Taking up arms against the government of the city.' },
    { code = 'PC 919',  label = 'Street Racing',                                    class = 'felony',      months = 15,  fine = 1800,  description = 'Taking part in a speed contest on a public road.' },
    { code = 'PC 921',  label = 'Driving Under the Influence Causing Injury',       class = 'felony',      months = 30,  fine = 4000,  description = 'Injuring another person while driving impaired.' },
    { code = 'PC 923',  label = 'Hit and Run Causing Injury',                       class = 'felony',      months = 25,  fine = 3000,  description = 'Leaving the scene of a collision in which somebody was injured.' },
    { code = 'PC 925',  label = 'Reckless Evading',                                 class = 'felony',      months = 18,  fine = 1800,  description = 'Fleeing police in a vehicle with disregard for public safety.' },
    { code = 'PC 931',  label = 'Piloting Without a Licence',                       class = 'felony',      months = 20,  fine = 1800,  description = 'Operating an aircraft without holding a pilot licence.' },
    { code = 'PC 932',  label = 'Flying Into Restricted Airspace',                  class = 'felony',      months = 22,  fine = 2000,  description = 'Entering controlled airspace without clearance.' },
    { code = 'PC 1006', label = 'Poaching',                                         class = 'felony',      months = 20,  fine = 1500,  description = 'Taking a protected species.' },
    { code = 'PC 1009', label = 'Environmental Contamination',                      class = 'felony',      months = 26,  fine = 6000,  description = 'Releasing hazardous material into the land, the air or the water.' },

    -- Misdemeanors
    { code = 'PC 101',  label = 'Simple Assault',                                   class = 'misdemeanor', months = 6,   fine = 500,   description = 'Unwanted physical contact with another person that causes no lasting injury.' },
    { code = 'PC 102',  label = 'Assault',                                          class = 'misdemeanor', months = 12,  fine = 900,   description = 'Deliberately causing injury to another person without using a weapon.' },
    { code = 'PC 107',  label = 'Criminal Threats',                                 class = 'misdemeanor', months = 8,   fine = 600,   description = 'Stating an intent to cause harm to a person or to their property.' },
    { code = 'PC 108',  label = 'Reckless Endangerment',                            class = 'misdemeanor', months = 12,  fine = 1000,  description = 'Acting with disregard for safety in a way that puts another at risk of serious injury.' },
    { code = 'PC 118',  label = 'Unlawful Imprisonment',                            class = 'misdemeanor', months = 10,  fine = 700,   description = 'Holding a person against their will without lawful authority.' },
    { code = 'PC 125',  label = 'Harassment',                                       class = 'misdemeanor', months = 10,  fine = 600,   description = 'Repeated unwanted contact or verbal abuse directed at a person.' },
    { code = 'PC 202',  label = 'Grand Theft',                                      class = 'misdemeanor', months = 10,  fine = 800,   description = 'Taking property of substantial value.' },
    { code = 'PC 209',  label = 'Burglary',                                         class = 'misdemeanor', months = 12,  fine = 700,   description = 'Entering a building unlawfully intending to commit a crime inside it.' },
    { code = 'PC 215',  label = 'Possession of Stolen Property',                    class = 'misdemeanor', months = 10,  fine = 600,   description = 'Holding property known or reasonably believed to be stolen.' },
    { code = 'PC 217',  label = 'Possession of Burglary Tools',                     class = 'misdemeanor', months = 10,  fine = 600,   description = 'Carrying equipment intended for forced entry or theft.' },
    { code = 'PC 219',  label = 'Possession of Marked Currency',                    class = 'misdemeanor', months = 12,  fine = 900,   description = 'Holding cash known to be the proceeds of a crime.' },
    { code = 'PC 301',  label = 'Fraud',                                            class = 'misdemeanor', months = 10,  fine = 700,   description = 'Deceiving another person for financial gain.' },
    { code = 'PC 302',  label = 'Forgery',                                          class = 'misdemeanor', months = 14,  fine = 900,   description = 'Producing or altering a document in order to pass it off as genuine.' },
    { code = 'PC 304',  label = 'Possession of Stolen Identification',              class = 'misdemeanor', months = 10,  fine = 700,   description = 'Holding identification documents belonging to another person.' },
    { code = 'PC 305',  label = 'Possession of Government Identification',          class = 'misdemeanor', months = 18,  fine = 1800,  description = 'Holding identification issued to a government employee.' },
    { code = 'PC 306',  label = 'Impersonating Another Person',                     class = 'misdemeanor', months = 14,  fine = 1200,  description = 'Falsely presenting yourself as another named individual.' },
    { code = 'PC 403',  label = 'Vandalism of Government Property',                 class = 'misdemeanor', months = 15,  fine = 1200,  description = 'Deliberately damaging property belonging to the city.' },
    { code = 'PC 404',  label = 'Criminal Damage',                                  class = 'misdemeanor', months = 12,  fine = 900,   description = 'Destroying property belonging to another person.' },
    { code = 'PC 407',  label = 'Trespassing',                                      class = 'misdemeanor', months = 8,   fine = 400,   description = 'Remaining on property where you have no lawful right to be.' },
    { code = 'PC 409',  label = 'Tampering With a Vehicle',                         class = 'misdemeanor', months = 12,  fine = 800,   description = 'Interfering with the normal function of another person vehicle.' },
    { code = 'PC 501',  label = 'Resisting Arrest',                                 class = 'misdemeanor', months = 6,   fine = 400,   description = 'Physically refusing to submit to a lawful arrest.' },
    { code = 'PC 502',  label = 'Evading on Foot',                                  class = 'misdemeanor', months = 8,   fine = 500,   description = 'Fleeing from officers attempting a lawful detention.' },
    { code = 'PC 503',  label = 'Obstruction of Justice',                           class = 'misdemeanor', months = 10,  fine = 600,   description = 'Acting in a way that hinders a lawful investigation.' },
    { code = 'PC 507',  label = 'False Reporting',                                  class = 'misdemeanor', months = 10,  fine = 800,   description = 'Reporting a crime or an emergency that did not take place.' },
    { code = 'PC 510',  label = 'Contempt of Court',                                class = 'misdemeanor', months = 12,  fine = 1500,  description = 'Disrupting or defying the authority of a court in session.' },
    { code = 'PC 511',  label = 'Failure to Appear',                                class = 'misdemeanor', months = 15,  fine = 1500,  description = 'Failing to attend a court hearing you were ordered to attend.' },
    { code = 'PC 512',  label = 'Violating a Court Order',                          class = 'misdemeanor', months = 12,  fine = 1200,  description = 'Breaching a condition imposed by a court.' },
    { code = 'PC 520',  label = 'Harbouring a Fugitive',                            class = 'misdemeanor', months = 12,  fine = 1200,  description = 'Sheltering a person known to be wanted.' },
    { code = 'PC 521',  label = 'Aiding and Abetting',                              class = 'misdemeanor', months = 15,  fine = 700,   description = 'Assisting or encouraging another person to commit a crime.' },
    { code = 'PC 522',  label = 'Conspiracy',                                       class = 'misdemeanor', months = 12,  fine = 700,   description = 'Agreeing with another person to commit a crime.' },
    { code = 'PC 524',  label = 'Failure to Provide Identification',                class = 'misdemeanor', months = 12,  fine = 1000,  description = 'Refusing to identify yourself when lawfully required to do so.' },
    { code = 'PC 604',  label = 'Public Indecency',                                 class = 'misdemeanor', months = 8,   fine = 700,   description = 'Exposing yourself in a public place.' },
    { code = 'PC 607',  label = 'Unlawful Assembly',                                class = 'misdemeanor', months = 10,  fine = 800,   description = 'Gathering in numbers at a location that requires prior approval.' },
    { code = 'PC 611',  label = 'Solicitation',                                     class = 'misdemeanor', months = 8,   fine = 500,   description = 'Offering or arranging an unlawful service in a public place.' },
    { code = 'PC 612',  label = 'Illegal Gambling',                                 class = 'misdemeanor', months = 12,  fine = 1200,  description = 'Operating or taking part in an unlicensed game of chance.' },
    { code = 'PC 613',  label = 'Operating an Unlicensed Business',                 class = 'misdemeanor', months = 10,  fine = 1000,  description = 'Trading without the licence the city requires.' },
    { code = 'PC 701',  label = 'Possession of Marijuana',                          class = 'misdemeanor', months = 5,   fine = 300,   description = 'Holding a small quantity of marijuana for personal use.' },
    { code = 'PC 702',  label = 'Cultivation of Marijuana',                         class = 'misdemeanor', months = 10,  fine = 800,   description = 'Growing marijuana plants without a licence.' },
    { code = 'PC 706',  label = 'Possession of Cocaine',                            class = 'misdemeanor', months = 7,   fine = 500,   description = 'Holding a small quantity of cocaine for personal use.' },
    { code = 'PC 709',  label = 'Possession of Methamphetamine',                    class = 'misdemeanor', months = 7,   fine = 500,   description = 'Holding a small quantity of methamphetamine for personal use.' },
    { code = 'PC 712',  label = 'Possession of Heroin',                             class = 'misdemeanor', months = 8,   fine = 600,   description = 'Holding a small quantity of heroin for personal use.' },
    { code = 'PC 715',  label = 'Possession of Ecstasy',                            class = 'misdemeanor', months = 7,   fine = 500,   description = 'Holding a small quantity of ecstasy for personal use.' },
    { code = 'PC 718',  label = 'Possession of Prescription Medication',            class = 'misdemeanor', months = 6,   fine = 400,   description = 'Holding prescription medication issued to somebody else.' },
    { code = 'PC 721',  label = 'Possession of Psilocybin',                         class = 'misdemeanor', months = 6,   fine = 400,   description = 'Holding a small quantity of psilocybin for personal use.' },
    { code = 'PC 723',  label = 'Sale of a Controlled Substance',                   class = 'misdemeanor', months = 12,  fine = 1200,  description = 'Selling a controlled substance in a personal quantity.' },
    { code = 'PC 811',  label = 'Possession of Illegal Firearm Modifications',      class = 'misdemeanor', months = 10,  fine = 400,   description = 'Holding attachments that are unlawful to fit to a firearm.' },
    { code = 'PC 812',  label = 'Brandishing a Weapon',                             class = 'misdemeanor', months = 14,  fine = 600,   description = 'Deliberately displaying a weapon in order to intimidate.' },
    { code = 'PC 813',  label = 'Criminal Use of a Weapon',                         class = 'misdemeanor', months = 12,  fine = 700,   description = 'Using a weapon in the course of committing another offence.' },
    { code = 'PC 814',  label = 'Discharging a Firearm in Public',                  class = 'misdemeanor', months = 15,  fine = 1200,  description = 'Firing a weapon in a public place without lawful cause.' },
    { code = 'PC 918',  label = 'Reckless Driving',                                 class = 'misdemeanor', months = 10,  fine = 800,   description = 'Driving with deliberate disregard for the safety of others.' },
    { code = 'PC 920',  label = 'Driving Under the Influence',                      class = 'misdemeanor', months = 8,   fine = 900,   description = 'Operating a vehicle while impaired.' },
    { code = 'PC 922',  label = 'Hit and Run',                                      class = 'misdemeanor', months = 12,  fine = 900,   description = 'Leaving the scene after striking a person, a vehicle or property.' },
    { code = 'PC 924',  label = 'Evading in a Vehicle',                             class = 'misdemeanor', months = 10,  fine = 800,   description = 'Failing to stop for a marked police vehicle.' },
    { code = 'PC 927',  label = 'Driving While Suspended',                          class = 'misdemeanor', months = 10,  fine = 1000,  description = 'Operating a vehicle while your licence is suspended.' },
    { code = 'PC 930',  label = 'Unlawful Use of a Motor Vehicle',                  class = 'misdemeanor', months = 10,  fine = 800,   description = 'Using a vehicle for a purpose the owner did not permit.' },
    { code = 'PC 1004', label = 'Hunting With a Prohibited Weapon',                 class = 'misdemeanor', months = 10,  fine = 800,   description = 'Taking game with a weapon not approved for hunting.' },
    { code = 'PC 1005', label = 'Exceeding the Bag Limit',                          class = 'misdemeanor', months = 10,  fine = 1000,  description = 'Taking more game than the season allows.' },
    { code = 'PC 1007', label = 'Animal Cruelty',                                   class = 'misdemeanor', months = 12,  fine = 800,   description = 'Causing unnecessary suffering to an animal.' },
    { code = 'PC 1008', label = 'Illegal Dumping',                                  class = 'misdemeanor', months = 12,  fine = 1500,  description = 'Discharging waste outside a licensed facility.' },

    -- Infractions
    { code = 'PC 201',  label = 'Petty Theft',                                      class = 'infraction',  months = 0,   fine = 250,   description = 'Taking property of minor value.' },
    { code = 'PC 214',  label = 'Leaving Without Paying',                           class = 'infraction',  months = 0,   fine = 400,   description = 'Leaving a business without paying for goods or services received.' },
    { code = 'PC 401',  label = 'Littering',                                        class = 'infraction',  months = 0,   fine = 200,   description = 'Discarding refuse outside a designated bin.' },
    { code = 'PC 402',  label = 'Vandalism',                                        class = 'infraction',  months = 0,   fine = 350,   description = 'Deliberately damaging or defacing property.' },
    { code = 'PC 508',  label = 'Misuse of Emergency Services',                     class = 'infraction',  months = 0,   fine = 600,   description = 'Using an emergency line or service for a non-emergency.' },
    { code = 'PC 523',  label = 'Disobeying a Lawful Order',                        class = 'infraction',  months = 0,   fine = 700,   description = 'Refusing to comply with a lawful instruction from an officer.' },
    { code = 'PC 601',  label = 'Disorderly Conduct',                               class = 'infraction',  months = 0,   fine = 250,   description = 'Behaving in a way that creates a hazardous or offensive condition in public.' },
    { code = 'PC 602',  label = 'Disturbing the Peace',                             class = 'infraction',  months = 0,   fine = 350,   description = 'Behaving in a way that disrupts public order or the quiet of a neighbourhood.' },
    { code = 'PC 603',  label = 'Public Intoxication',                              class = 'infraction',  months = 0,   fine = 400,   description = 'Being intoxicated in public to the point of being a risk to yourself or others.' },
    { code = 'PC 605',  label = 'Loitering',                                        class = 'infraction',  months = 0,   fine = 200,   description = 'Remaining without purpose in a place after being asked to move on.' },
    { code = 'PC 606',  label = 'Loitering on Government Property',                 class = 'infraction',  months = 0,   fine = 500,   description = 'Remaining without business inside or around a government facility.' },
    { code = 'PC 610',  label = 'Anti-Mask Violation',                              class = 'infraction',  months = 0,   fine = 700,   description = 'Concealing your face inside a restricted zone.' },
    { code = 'PC 614',  label = 'Noise Violation',                                  class = 'infraction',  months = 0,   fine = 250,   description = 'Producing sound above the level permitted for the area and the hour.' },
    { code = 'PC 727',  label = 'Possession of Drug Paraphernalia',                 class = 'infraction',  months = 0,   fine = 250,   description = 'Holding equipment intended for the use of a controlled substance.' },
    { code = 'PC 901',  label = 'Third Degree Speeding',                            class = 'infraction',  months = 0,   fine = 200,   description = 'Exceeding the posted limit by up to fifteen miles per hour.' },
    { code = 'PC 902',  label = 'Second Degree Speeding',                           class = 'infraction',  months = 0,   fine = 400,   description = 'Exceeding the posted limit by up to thirty five miles per hour.' },
    { code = 'PC 903',  label = 'First Degree Speeding',                            class = 'infraction',  months = 0,   fine = 750,   description = 'Exceeding the posted limit by more than thirty five miles per hour.' },
    { code = 'PC 904',  label = 'Failure to Stop',                                  class = 'infraction',  months = 0,   fine = 500,   description = 'Failing to stop at a sign, a signal or a lawful direction.' },
    { code = 'PC 905',  label = 'Failure to Obey a Traffic Device',                 class = 'infraction',  months = 0,   fine = 150,   description = 'Ignoring a signal, a sign or a road marking.' },
    { code = 'PC 906',  label = 'Failure to Maintain Lane',                         class = 'infraction',  months = 0,   fine = 250,   description = 'Drifting out of the marked lane.' },
    { code = 'PC 907',  label = 'Illegal Turn',                                     class = 'infraction',  months = 0,   fine = 150,   description = 'Turning where the movement is prohibited.' },
    { code = 'PC 908',  label = 'Illegal U-Turn',                                   class = 'infraction',  months = 0,   fine = 150,   description = 'Reversing direction where the movement is prohibited.' },
    { code = 'PC 909',  label = 'Illegal Passing',                                  class = 'infraction',  months = 0,   fine = 300,   description = 'Overtaking in a manner or a place that is prohibited.' },
    { code = 'PC 910',  label = 'Failure to Yield',                                 class = 'infraction',  months = 0,   fine = 300,   description = 'Failing to give way where the road requires it.' },
    { code = 'PC 911',  label = 'Failure to Yield to an Emergency Vehicle',         class = 'infraction',  months = 0,   fine = 600,   description = 'Failing to give way to a responding emergency vehicle.' },
    { code = 'PC 912',  label = 'Unsafe Lane Change',                               class = 'infraction',  months = 0,   fine = 250,   description = 'Changing lanes without leaving safe space for other traffic.' },
    { code = 'PC 913',  label = 'Driving Without Headlights',                       class = 'infraction',  months = 0,   fine = 250,   description = 'Operating a vehicle after dark without working lights.' },
    { code = 'PC 914',  label = 'Failure to Signal',                                class = 'infraction',  months = 0,   fine = 150,   description = 'Turning or changing lanes without signalling the movement.' },
    { code = 'PC 915',  label = 'Unauthorised Parking',                             class = 'infraction',  months = 0,   fine = 300,   description = 'Leaving a vehicle where parking is not permitted.' },
    { code = 'PC 916',  label = 'Abandoned Vehicle',                                class = 'infraction',  months = 0,   fine = 250,   description = 'Leaving a non-functional vehicle on the roadway.' },
    { code = 'PC 917',  label = 'Negligent Driving',                                class = 'infraction',  months = 0,   fine = 350,   description = 'Driving without proper attention to the road.' },
    { code = 'PC 926',  label = 'Driving Without a Licence',                        class = 'infraction',  months = 0,   fine = 500,   description = 'Operating a vehicle without holding a valid licence.' },
    { code = 'PC 928',  label = 'Operating an Unregistered Vehicle',                class = 'infraction',  months = 0,   fine = 350,   description = 'Operating a vehicle whose registration has lapsed.' },
    { code = 'PC 929',  label = 'Jaywalking',                                       class = 'infraction',  months = 0,   fine = 150,   description = 'Crossing a roadway outside a marked crossing.' },
    { code = 'PC 933',  label = 'Operating a Vessel Without a Licence',             class = 'infraction',  months = 0,   fine = 500,   description = 'Operating a boat without holding a valid licence.' },
    { code = 'PC 1001', label = 'Hunting Without a Licence',                        class = 'infraction',  months = 0,   fine = 450,   description = 'Taking game without holding a hunting licence.' },
    { code = 'PC 1002', label = 'Hunting in a Restricted Area',                     class = 'infraction',  months = 0,   fine = 500,   description = 'Taking game in an area that is closed to hunting.' },
    { code = 'PC 1003', label = 'Hunting Outside Permitted Hours',                  class = 'infraction',  months = 0,   fine = 450,   description = 'Taking game outside the hours set for the season.' },
}
